version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

  pre_build:
    commands:
      - echo Installing dependencies...
      - cd feedback-app
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: feedback-app/dist
  discard-paths: yes
cache:
  paths:
    - 'node_modules/**/*'